sudo: required
services:
  - docker

before_install:
  - docker build -t jamesyu608/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jamesyu608/react-test npm test -- --coverage

after_success:
  - docker build -t jamesyu608/mutli-client ./client
  - docker build -t jamesyu608/mutli-nginx ./nginx
  - docker build -t jamesyu608/mutli-server ./server
  - docker build -t jamesyu608/mutli-worker ./worker
  # Log in to the docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push jamesyu608/mutli-client
  - docker push jamesyu608/mutli-nginx
  - docker push jamesyu608/mutli-server
  - docker push jamesyu608/mutli-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-972003514821
  bucket_path: docker-mutli
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY